/* eslint-disable react/no-unescaped-entities */
/* eslint-disable */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Avatar from '../components/Avatar'
import Footer from '../components/Footer'
import {Squares2X2Icon, MicrophoneIcon, MagnifyingGlassIcon} from '@heroicons/react/24/solid'
import { useRef } from 'react'
import {useRouter} from 'next/router'


export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault()
    const term = searchInputRef.current.value;
    
    if(!term) return;

    router.push(`/search?term=${term}`)
  }

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* {Header} */}
      <header className='flex w-full p-5 justify-between text-gray-700'>
        {/* {left part of header} */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* {right part of header} */}
        <div className='flex space-x-4 items-center'>
            <p className='link'>Gmail</p>
            <p className='link'>Images</p>

            {/* {Icon} */}
            <Squares2X2Icon  className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer'/>

            {/* {Avatar} */}
            <Avatar url='https://c4.wallpaperflare.com/wallpaper/430/896/23/one-piece-roronoa-zoro-hd-wallpaper-preview.jpg'/>
        </div>
      </header>

      {/* {body} */}
      <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
        <Image 
          src='https://static.vecteezy.com/system/resources/previews/010/930/001/original/google-logo-icon-illustration-free-vector.jpg'
          height={100}
          width={300} 
          alt={''}        
          />
          <div className='flex w-full mt-2 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center
          sm:max-w-xl lg:max-w-2xl'>
             <MagnifyingGlassIcon className='h-5 mr-3 text-gray-500'/>
             <input ref={searchInputRef} type='text' className='focus:outline-none flex-grow'/>
             <MicrophoneIcon className='h-5'/>
          </div>

          <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
            <button onClick={search} className='btn'>Google Search</button>

            <button onClick={search} className='btn'>I'm Feeling Lucky</button>
          </div>
      </form>

      {/* {footer} */}
      <Footer />
    </div>
  )
}
